"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django.core.management.utils import get_random_secret_key

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load from environment variable or generate a temporary one for development
SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-key-only-change-in-production-' + get_random_secret_key()[:20])

# Secret Chamber encryption key (load from environment or use development key)
# For production: generate with: python -c "import os; import base64; print(base64.b64encode(os.urandom(32)))"
SECRET_CHAMBER_KEY = os.environ.get('SECRET_CHAMBER_KEY', b'J8f5k2L9n3P6q1R4s7T0u9V2x5Y8z1A4b7C0d3F6g9H2')
if isinstance(SECRET_CHAMBER_KEY, str):
    SECRET_CHAMBER_KEY = SECRET_CHAMBER_KEY.encode('utf-8')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,::1,testserver').split(',')


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'compressor',  # CSS/JS compression and minification
    'blog.apps.BlogConfig',
    'blog.secret_chamber.apps.SecretChamberConfig',
    
    # Security monitoring apps (install these packages first)
    # 'django_otp',
    # 'django_otp.plugins.otp_totp', 
    # 'django_otp.plugins.otp_static',
    # 'corsheaders',
    # 'csp',
)

# =============================================================================
# CACHING CONFIGURATION
# =============================================================================
# ⚠️ CRITICAL PERFORMANCE FIX: Implementing caching (was previously missing)
# This addresses one of the major architectural issues identified

# For development: Local memory cache
# For production: Use Redis (install django-redis: pip install django-redis redis)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'lms-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        },
        'TIMEOUT': 300,  # 5 minutes default
    }
}

# Production Redis cache (uncomment and configure for production with Redis):
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         },
#         'KEY_PREFIX': 'lms',
#         'TIMEOUT': 300,
#     }
# }

MIDDLEWARE = [
    # Core Django middleware
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static file serving with compression
    'django.contrib.sessions.middleware.SessionMiddleware', 
    
    # Security monitoring middleware (uncomment after installing dependencies)
    # 'blog.security_middleware.SecurityMonitoringMiddleware',
    
    # XSS Protection middleware - adds CSP headers and nonce support
    'blog.middleware.csp_middleware.CSPMiddleware',
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    
    # Tor detection middleware (uncomment after installing dependencies)  
    # 'blog.security_middleware.TorDetectionMiddleware',
    
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    # Authentication monitoring middleware (uncomment after installing dependencies)
    # 'blog.security_middleware.AuthenticationMonitoringMiddleware',
    
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.context_processors.theme_context',
                'blog.context_processors.available_themes_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database - Optimized Configuration for Performance and Integrity
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'OPTIONS': {
            'timeout': 30,  # 30 seconds timeout for better concurrency
            'init_command': '''
                PRAGMA journal_mode=WAL;
                PRAGMA synchronous=NORMAL;
                PRAGMA cache_size=1000000;
                PRAGMA temp_store=MEMORY;
                PRAGMA mmap_size=268435456;
                PRAGMA foreign_keys=ON;
                PRAGMA case_sensitive_like=ON;
                PRAGMA automatic_index=ON;
                PRAGMA optimize;
            '''
        }
    }
}

# Database connection pooling and optimization
DATABASE_CONNECTION_POOL_SIZE = 20
DATABASE_MAX_OVERFLOW = 10


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Bratislava'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB

# Assignment file upload security settings
MAX_ASSIGNMENT_FILE_SIZE = 50 * 1024 * 1024  # 50 MB for source code projects

# File upload security headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/courses/'
LOGOUT_REDIRECT_URL = '/'

# =============================================================================
# CACHING CONFIGURATION
# =============================================================================

# Django Cache Framework - Local Memory Cache for Development
# For production, switch to Redis: pip install django-redis redis
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'lms-cache',
        'TIMEOUT': 300,  # Default timeout: 5 minutes
        'KEY_PREFIX': 'lms',  # Prefix for all cache keys
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Production Redis Configuration (commented out - uncomment and configure for production):
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         },
#         'KEY_PREFIX': 'lms',
#         'TIMEOUT': 300,  # 5 minutes default
#     }
# }

# Cache timeout settings (in seconds)
CACHE_MIDDLEWARE_SECONDS = 300  # 5 minutes default
CACHE_MIDDLEWARE_KEY_PREFIX = 'lms'

# =============================================================================
# SECURITY MONITORING CONFIGURATION
# =============================================================================

# Basic security settings (ready to use)
SECURITY_RATE_LIMIT_REQUESTS = 100
SECURITY_RATE_LIMIT_WINDOW = 3600
SECURITY_MAX_FAILED_ATTEMPTS = 5
SECURITY_LOCKOUT_DURATION = 3600
SECURITY_TOR_POLICY = 'log'
SECURITY_SCAN_UPLOADS = True
SECURITY_DASHBOARD_ENABLED = True

# Enhanced password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,  # Enhanced security
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Session security (enhanced)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600

# CSRF protection (enhanced)
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'

# Additional security headers
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# =============================================================================
# PRODUCTION SECURITY NOTES
# =============================================================================

# For production, also set:
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True  
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# =============================================================================
# SECURITY PACKAGES TO INSTALL
# =============================================================================

# Run these commands to install security dependencies:
# pip install django-otp pyotp qrcode[pil]
# pip install django-ratelimit 
# pip install django-cors-headers
# pip install django-csp
# pip install rich tabulate
# pip install django-ipware user-agents
# pip install geoip2 python-whois

# After installing, uncomment the middleware and apps sections above

# =============================================================================
# STATIC FILE OPTIMIZATION (P1 - HIGH Priority)
# =============================================================================
# Whitenoise serves static files with compression and cache-busting
# Django-compressor minifies and combines CSS/JS files
# Target: 30-50% page load improvement, 60-80% file size reduction

# Use Whitenoise's compressed manifest storage for automatic cache-busting
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Allow Whitenoise to use Django's staticfiles finders
WHITENOISE_USE_FINDERS = True

# Enable Brotli compression (better than gzip, ~20% smaller)
WHITENOISE_BROTLI_SUPPORT = True

# Whitenoise will also serve gzip for older browsers
WHITENOISE_GZIP_SUPPORT = True

# Cache static files aggressively (1 year for versioned files)
WHITENOISE_MAX_AGE = 31536000  # 1 year in seconds

# Compress static files in production
COMPRESS_ENABLED = not DEBUG  # Enable compression when DEBUG=False

# Offline compression (run ./manage.py compress before deployment)
COMPRESS_OFFLINE = False  # Set to True for production deployments

# CSS minification filters
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',  # Fix relative URLs
    'compressor.filters.cssmin.rCSSMinFilter',            # Minify CSS
]

# JavaScript minification filters
COMPRESS_JS_FILTERS = [
    'compressor.filters.jsmin.JSMinFilter',  # Minify JavaScript
]

# Cache control for static files served by Whitenoise
WHITENOISE_INDEX_FILE = True

# Compressor output directory
COMPRESS_OUTPUT_DIR = 'cache'

# Add compressor finder to staticfiles finders
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',  # For django-compressor
)

# =============================================================================
# STATIC FILE OPTIMIZATION (P1)
# =============================================================================
