# Generated by Django 5.2.6 on 2025-10-10 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_forum_topic_forumpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Theme identifier', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable theme name', max_length=100)),
                ('theme_key', models.CharField(choices=[('terminal-green', 'Terminal Green'), ('dark-blue', 'Dark Blue'), ('light', 'Light'), ('cyberpunk', 'Cyberpunk'), ('matrix', 'Matrix')], max_length=20, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default theme for new users')),
                ('is_active', models.BooleanField(default=True, help_text='Theme is available for selection')),
                ('description', models.TextField(blank=True, help_text='Theme description')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Site Theme',
                'verbose_name_plural': 'Site Themes',
            },
        ),
        migrations.CreateModel(
            name='UserThemePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='blog.sitetheme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Theme Preference',
                'verbose_name_plural': 'User Theme Preferences',
            },
        ),
    ]
