# Generated by Django 5.2.6 on 2025-10-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_blogcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetheme',
            name='theme_key',
            field=models.CharField(choices=[('terminal-amber', 'Terminal Amber'), ('dark-blue', 'Dark Blue'), ('light', 'Light'), ('cyberpunk', 'Cyberpunk'), ('matrix', 'Matrix')], max_length=20, unique=True),
        ),
    ]
