# Generated by Django 5.2.6 on 2025-10-17 09:40

from django.db import migrations

def update_terminal_theme_data(apps, schema_editor):
    """Update theme data from terminal-green to terminal-amber"""
    SiteTheme = apps.get_model('blog', 'SiteTheme')
    
    # Update SiteTheme records
    SiteTheme.objects.filter(theme_key='terminal-green').update(
        theme_key='terminal-amber',
        name='terminal_amber',
        display_name='Terminal Amber'
    )
    
    # UserThemePreference will automatically use the updated SiteTheme through foreign key

def reverse_terminal_theme_data(apps, schema_editor):
    """Reverse the theme data changes"""
    SiteTheme = apps.get_model('blog', 'SiteTheme')
    
    # Reverse SiteTheme records
    SiteTheme.objects.filter(theme_key='terminal-amber').update(
        theme_key='terminal-green',
        name='terminal_green',
        display_name='Terminal Green'
    )
    
    # UserThemePreference will automatically use the updated SiteTheme through foreign key

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_sitetheme_theme_key'),
    ]

    operations = [
        migrations.RunPython(update_terminal_theme_data, reverse_terminal_theme_data),
    ]
