# Generated by Django 5.2.6 on 2025-10-18 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_database_optimizations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('general', 'General'), ('deadline', 'Assignment Deadline'), ('exam', 'Exam'), ('holiday', 'Holiday'), ('maintenance', 'System Maintenance'), ('meeting', 'Meeting'), ('workshop', 'Workshop'), ('announcement', 'Announcement')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Link to specific course (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'title'],
                'indexes': [models.Index(fields=['start_date', 'is_published'], name='blog_event_start_d_7ed163_idx'), models.Index(fields=['event_type', 'priority'], name='blog_event_event_t_ab2f50_idx'), models.Index(fields=['is_featured', 'start_date'], name='blog_event_is_feat_51fa9b_idx'), models.Index(fields=['course', 'start_date'], name='blog_event_course__8c215a_idx')],
            },
        ),
    ]
