# Generated by Django 5.2.6 on 2025-10-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='materials',
            field=models.FileField(blank=True, help_text='Event materials (PDF, DOC, etc.)', null=True, upload_to='event_materials/'),
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, help_text='Event poster image (JPG, PNG)', null=True, upload_to='event_posters/'),
        ),
    ]
