# Generated by Django 5.2.6 on 2025-10-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_event_materials_event_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('registered', 'Registered Users Only - Login required')], default='registered', help_text='Who can view this event', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Event name (max 128 characters)', max_length=128),
        ),
    ]
