# Generated by Django 5.2.6 on 2025-10-20 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_event_visibility_alter_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Event type name', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('color', models.CharField(default='#32cd32', help_text='Hex color code (e.g., #32cd32)', max_length=7)),
                ('background_color', models.CharField(default='#0f1419', help_text='Background hex color', max_length=7)),
                ('icon', models.CharField(default='fas fa-calendar', help_text='FontAwesome icon class', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of this event type')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='custom_background',
            field=models.CharField(blank=True, help_text='Custom background color', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_color',
            field=models.CharField(blank=True, help_text='Custom hex color (overrides event type)', max_length=7),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('general', 'General'), ('deadline', 'Assignment Deadline'), ('exam', 'Exam'), ('holiday', 'Holiday'), ('maintenance', 'System Maintenance'), ('meeting', 'Meeting'), ('workshop', 'Workshop'), ('announcement', 'Announcement')], default='general', help_text='Legacy event type (use event_type_new for custom types)', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type_new',
            field=models.ForeignKey(blank=True, help_text='Customizable event type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='blog.eventtype'),
        ),
    ]
