# Generated by Django 5.2.6 on 2025-10-20 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_eventtype_event_custom_background_event_custom_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='linked_lesson',
            field=models.ForeignKey(blank=True, help_text='Direct lesson link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_events', to='blog.lesson'),
        ),
        migrations.AddField(
            model_name='event',
            name='obsidian_link',
            field=models.CharField(blank=True, help_text='Obsidian-style link: [[Course Name - Lesson Title]] or lesson URL', max_length=255),
        ),
    ]
