# Generated by Django 5.2.6 on 2025-10-20 08:28

import blog.models
import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_event_linked_lesson_event_obsidian_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file_attachment',
            field=models.FileField(blank=True, help_text='Optional assignment file (instructions, templates, etc.)', upload_to=blog.models.assignment_upload_path, validators=[blog.validators.validate_assignment_file]),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(help_text='Educational materials: documents, source code, images, videos. Max 50MB.', upload_to=blog.models.course_material_upload_path, validators=[blog.validators.validate_assignment_file]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file_submission',
            field=models.FileField(blank=True, help_text='Allowed: Source code (.py, .go, .rs, .js, .java, .cpp), documents (.pdf, .txt, .md), images, archives (.zip). Max 50MB.', upload_to=blog.models.submission_upload_path, validators=[blog.validators.validate_assignment_file]),
        ),
    ]
