# Generated by Django 5.2.6 on 2025-10-22 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_add_file_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exclude_holidays',
            field=models.BooleanField(default=True, help_text='Skip events that fall on holidays'),
        ),
        migrations.AddField(
            model_name='event',
            name='exclude_weekends',
            field=models.BooleanField(default=False, help_text='Skip weekend occurrences (for daily patterns)'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Create recurring events'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_occurrences',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of occurrences (alternative to end date)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='occurrence_date',
            field=models.DateField(blank=True, help_text='Original date for this occurrence (for modified instances)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, help_text='Parent event for recurring series', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='blog.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_days',
            field=models.CharField(blank=True, help_text='Days of week for recurring events (mon,tue,wed,thu,fri,sat,sun)', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_end_date',
            field=models.DateTimeField(blank=True, help_text='When should recurring events stop?', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_interval',
            field=models.PositiveIntegerField(default=1, help_text='Repeat every N intervals (e.g., every 2 weeks)'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly (Every 2 weeks)'), ('monthly', 'Monthly'), ('custom', 'Custom Pattern')], help_text='How often should this event repeat?', max_length=20),
        ),
    ]
