# Generated by Django 5.2.6 on 2025-10-25 05:02

import blog.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alertrule_threatintelligence_systemmetrics_auditlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Blog featured image (EXIF metadata will be automatically removed for privacy)', null=True, storage=blog.utils.storage.MediaStorage(), upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, help_text='Event poster image (JPG, PNG) - EXIF metadata will be automatically removed for privacy', null=True, storage=blog.utils.storage.MediaStorage(), upload_to='event_posters/'),
        ),
    ]
