# Generated by Django 5.2.6 on 2025-10-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_blogpost_featured_image_alter_event_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, help_text='Zoom meeting ID (e.g., 123-456-7890)', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='zoom_meeting_password',
            field=models.CharField(blank=True, help_text='Zoom meeting password (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='zoom_meeting_url',
            field=models.URLField(blank=True, help_text='Zoom meeting join URL', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='zoom_webinar_url',
            field=models.URLField(blank=True, help_text='Zoom webinar registration URL', max_length=500),
        ),
    ]
