# Generated by Django 5.2.7 on 2025-11-19 08:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_add_zoom_fields_to_event'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('secret_chamber', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentQuarantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quarantine_reason', models.TextField(help_text='Detailed explanation for why this content was quarantined')),
                ('quarantine_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Quarantine'), ('RESOLVED_RESTORE', 'Resolved - Content Restored'), ('RESOLVED_DELETE', 'Resolved - Content Deleted'), ('RESOLVED_EXTENDED', 'Resolved - Quarantine Extended')], default='ACTIVE', max_length=20)),
                ('resolution_deadline', models.DateTimeField(blank=True, help_text='Deadline for poll voting and resolution', null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('linked_poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantined_content', to='secret_chamber.adminpoll')),
                ('quarantined_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantined_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Quarantine',
                'verbose_name_plural': 'Content Quarantines',
                'ordering': ['-quarantine_date'],
            },
        ),
        migrations.CreateModel(
            name='QuarantineDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_result', models.CharField(choices=[('RESTORE', 'Restore Content'), ('DELETE', 'Delete Permanently'), ('EXTEND', 'Extend Quarantine')], help_text='Majority vote outcome from Secret Chamber poll', max_length=20)),
                ('decision_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_taken', models.CharField(choices=[('RESTORED', 'Content Restored'), ('DELETED', 'Content Deleted'), ('EXTENDED', 'Quarantine Extended')], help_text='Action performed based on poll result', max_length=20)),
                ('decision_notes', models.TextField(blank=True, help_text='Additional context or reasoning for the decision')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_decisions', to=settings.AUTH_USER_MODEL)),
                ('quarantine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='blog.contentquarantine')),
            ],
            options={
                'verbose_name': 'Quarantine Decision',
                'verbose_name_plural': 'Quarantine Decisions',
                'ordering': ['-decision_date'],
            },
        ),
        migrations.AddIndex(
            model_name='contentquarantine',
            index=models.Index(fields=['content_type', 'object_id'], name='blog_conten_content_4f0b91_idx'),
        ),
        migrations.AddIndex(
            model_name='contentquarantine',
            index=models.Index(fields=['status', 'quarantine_date'], name='blog_conten_status_f27a05_idx'),
        ),
    ]
