# Generated by Django 5.2.7 on 2025-12-01 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_contentquarantine_quarantinedecision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date', 'visibility'], name='blog_event_start_d_be4cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published', 'start_date', 'visibility'], name='blog_event_is_publ_0b174e_idx'),
        ),
    ]
