# Generated by Django 5.2.6 on 2025-10-27 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Poll question', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional context')),
                ('poll_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('yes_no', 'Yes/No Vote'), ('rating', 'Rating (1-10)'), ('open_response', 'Open Response')], default='multiple_choice', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(help_text='When voting closes')),
                ('is_active', models.BooleanField(default=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_admin_polls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Poll',
                'verbose_name_plural': 'Admin Polls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminPollAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('poll_created', 'Poll Created'), ('vote_cast', 'Vote Cast'), ('poll_closed', 'Poll Closed'), ('report_generated', 'Report Generated')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secret_chamber.adminpoll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdminPollReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Report content in markdown')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='secret_chamber.adminpoll')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='secret_chamber.adminpoll')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('poll', 'option_text')},
            },
        ),
        migrations.CreateModel(
            name='AdminVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rating_value', models.IntegerField(blank=True, help_text='1-10 rating', null=True)),
                ('text_response', models.TextField(blank=True, help_text='Open response or comment')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_votes', to='secret_chamber.adminpoll')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_votes', to=settings.AUTH_USER_MODEL)),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secret_chamber.polloption')),
            ],
            options={
                'ordering': ['timestamp'],
                'unique_together': {('poll', 'voter')},
            },
        ),
    ]
